### ISSUE TITLE
Cannot run servlet example

### ISSUE THREAD

**Issue by jamesnetherton** [wildfly-swarm/example-servlet#1]
Am I missing something obvious? I've cloned this repo, built the code and tried to execute the resulting jar. I cannot get past the following (the dependency it's moaning about is present in my local m2 repo):

```
08:42:42,514 ERROR [org.jboss.msc.service.fail] (MSC service thread 1-7) MSC000001: Failed to start service jboss.as: org.jboss.msc.service.StartException in service jboss.as: Failed to start service
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1904)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.jboss.modules.ModuleLoadError: Error loading module from modules/system/layers/base/org/picketbox/main/module.xml
	at org.jboss.modules.ModuleLoadException.toError(ModuleLoadException.java:74)
	at org.jboss.modules.Module.getPathsUnchecked(Module.java:1384)
	at org.jboss.modules.Module.loadModuleClass(Module.java:555)
	at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:197)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:455)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassChecked(ConcurrentClassLoader.java:404)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:385)
	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:130)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at org.jboss.modules.ModuleClassLoader.doDefineOrLoadClass(ModuleClassLoader.java:353)
	at org.jboss.modules.ModuleClassLoader.defineClass(ModuleClassLoader.java:432)
	at org.jboss.modules.ModuleClassLoader.loadClassLocal(ModuleClassLoader.java:269)
	at org.jboss.modules.ModuleClassLoader$1.loadClassLocal(ModuleClassLoader.java:77)
	at org.jboss.modules.Module.loadModuleClass(Module.java:560)
	at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:197)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:455)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassChecked(ConcurrentClassLoader.java:404)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:385)
	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:130)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:370)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at org.jboss.as.server.ApplicationServerService.service(ApplicationServerService.java:224)
	at org.jboss.as.server.ApplicationServerService.start(ApplicationServerService.java:153)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1948)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1881)
	... 3 more
Caused by: org.jboss.modules.xml.XmlPullParserException: Failed to resolve artifact '${org.picketbox:picketbox}' (position: END_TAG seen ...<resources>\n        <artifact name="${org.picketbox:picketbox}"/>... @32:54) 
	at org.jboss.modules.ModuleXmlParser.parseArtifact(ModuleXmlParser.java:890)
	at org.jboss.modules.ModuleXmlParser.parseResources(ModuleXmlParser.java:729)
	at org.jboss.modules.ModuleXmlParser.parseModuleContents(ModuleXmlParser.java:494)
	at org.jboss.modules.ModuleXmlParser.parseDocument(ModuleXmlParser.java:287)
	at org.jboss.modules.ModuleXmlParser.parseModuleXml(ModuleXmlParser.java:150)
	at org.jboss.modules.BootModuleFinder.findModule(BootModuleFinder.java:48)

```

**Comment by eprogramming** [comment]
+1

18:45:45,917 ERROR [stderr] (main) Caused by: org.jboss.modules.xml.XmlPullParserException: Failed to resolve artifact '${org.picketbox:picketbox}' (position: END_TAG seen ...<resources>\n        <artifact name="${org.picketbox:picketbox}"/>... @32:54) 

https://asciinema.org/a/19767

**Comment by jamezp** [comment]
This is fixed upstream in the wildfly-swarm project. See https://github.com/wildfly-swarm/wildfly-swarm/issues/7.
